[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_GEMINI_API_KEY = "AIzaSyC3Zzlv5are_c7qayolflfgbRI7WXISadc"
  REACT_APP_WEATHER_API_KEY = "236c471e864a13bfe824100061a58d23"
  CI = "false" 