services:
  - type: web
    name: mega-chef-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000


